#!/bin/bash
# Text input script by TDGalea.

[[ -z "$1" ]] && printf "Input what text?\n" >&2 && exit 2

luna-send -f -n 1 luna://com.webos.service.ime/insertText '{"text": "'"$*"'", "replace": true}'
exit $?
